syntax enable
set background=dark
colorscheme gruvbox

set tabstop=4
set shiftwidth=4
set noexpandtab

highlight ExtraWhitespace ctermbg=gray guibg=gray
match ExtraWhitespace /\s\+$/

set whichwrap+=<,>,[,],h,l

set number

set mouse=a
