set packpath+=~/.vim
set number
set mouse=a
set nowrap
set list
set listchars=
set listchars+=precedes:«,extends:»
syntax enable

set background=dark
colorscheme gruvbox

set tabstop=4
set shiftwidth=4
set noexpandtab

highlight ExtraWhitespace ctermbg=gray guibg=gray
match ExtraWhitespace /\s\+$/

set whichwrap+=<,>,[,],h,l

command YA %y+

filetype plugin indent on

" horizontal split: Ctrl + w, h
nnoremap <C-w>h :split<CR>

" NERDTree
autocmd vimenter * NERDTree
autocmd BufEnter * if (winnr('$') == 1 && &filetype == 'nerdtree') | q | endif
nnoremap <C-n> :NERDTreeToggle<CR>

" YouCompleteMe
set runtimepath+=$HOME/YouCompleteMe
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/.ycm_extra_conf.py'
set completeopt-=preview
