set packpath+=~/.vim
set number
set mouse=a
set nowrap
set list
set listchars=
set listchars+=precedes:«,extends:»
syntax enable
colorscheme gruvbox
set background=dark

set tabstop=4
set shiftwidth=4
set noexpandtab

highlight ExtraWhitespace ctermbg=gray guibg=gray
match ExtraWhitespace /\s\+$/

set whichwrap+=<,>,[,],h,l

command YA %y+

filetype plugin indent on

" horizontal split: Ctrl + w, h
nnoremap <C-w>h :split<CR>

" YouCompleteMe
set runtimepath+=$HOME/YouCompleteMe
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/.ycm_extra_conf.py'
set completeopt-=preview
