general {

  lock_cmd = pidof hyprlock || hyprlock

}

listener {
    timeout = 150
    on-timeout = $HOME/.hyprland/brightness_fade.sh --dim 33
    on-resume = $HOME/.hyprland/brightness_fade.sh --restore
}

listener {

  timeout = 300
  on-timeout = loginctl lock-session

}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}


