$background = rgb(46, 34, 47)
$backgroundAlpha = 2e222f

$selection = rgb(62, 53, 70)
$selectionAlpha = 3e3546

$foreground = rgb(171, 148, 122)
$foregroundAlpha = ab947a

$comment = rgb(150, 108, 108)
$commentAlpha = 966c6c

$cyan = rgb(98, 85, 101)
$cyanAlpha = 625565

$blue = rgb(11, 138, 143)
$blueAlpha = 0b8a8f

$green = rgb(162, 169, 71)
$greenAlpha = a2a947

$orange = rgb(247, 150, 23)
$orangeAlpha = f79617

$pink = rgb(162, 75, 111)
$pinkAlpha = a24b6f

$purple = rgb(162, 75, 111)
$purpleAlpha = a24b6f

$red = rgb(179, 56, 49)
$redAlpha = b33831

$yellow = rgb(249, 194, 43)
$yellowAlpha = f9c22b
