[terminal]
shell = "/bin/bash"

[general]
import = ["~/.themes/alacritty-resurrect64/resurrect64.toml"]

[window]
opacity = 0.8

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 12

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
