name: Build OVim

on:
  workflow_dispatch:  # ← allows manual trigger

jobs:
  build-arch:
    name: Build OVim Arch Package
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3

      - name: Build Arch Package
        run: |
          pacman -Syu --noconfirm git base-devel neovim nodejs npm ripgrep fd tree
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          cd .packages/ovim
          tar -czf lvim.tar.gz -C ../../.config lvim  # ← added this line
          chown -R builder .
          tree -L 3 -a
          su builder -c "makepkg --clean --syncdeps --install --noconfirm"

  build-deb:
    name: Build OVim DEB Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build DEB Package
        run: |
          mkdir -p debbuild/DEBIAN
          cp .packages/ovim/debian/control debbuild/DEBIAN/
          mkdir -p debbuild/etc/skel/.config/lvim
          cp -r .config/lvim/* debbuild/etc/skel/.config/lvim/
          mkdir -p debbuild/usr/share/ovim
          cp .packages/ovim/ovim-install.sh debbuild/usr/share/ovim/
          chmod +x debbuild/usr/share/ovim/ovim-install.sh
          dpkg-deb --build debbuild ovim.deb

  upload:
    name: Upload to GitHub Release
    needs: [build-arch, build-deb]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            artifacts/ovim-arch/*.pkg.tar.zst
            artifacts/ovim-deb/ovim.deb
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
